### ISSUE TITLE
Individual Id's for fields

### ISSUE THREAD

**Issue by mga47** [fraggjkee/sms-confirmation-view#13]
Can you please add Id's when creating fields? I get issue from QA team. 

> In Verification  code screen resource-id Attributes are missing. It is blocking me locate OTP fields and  automate Verification code screen flow.  Please add resource-id's for every  OTP fields

**Comment by fraggjkee** [comment]
What "fields" are we talking about here? Individual cells (with single digits) or the overall "sms confirmation view" component?

**Comment by mga47** [comment]
It's about individual cells, not the whole component.

**Comment by fraggjkee** [comment]
Hm... Maybe I'm missing something here, but why do they need to validate
individual symbols? Can't you guys just assign some ID to the
`SmsConfirmationView` itself and then in your automation tests locate that
view and check the actual entered code via the `enteredCode` property?

**Comment by fraggjkee** [comment]
I view this component as a kind of EditText so it just provides the text
(code) that is currently entered, individual cells are internal details
that can be changed to let's say 1 single drawing phase without actual
subviews, in this case it won't technically be possible to assign
distinct IDs to each symbol.

**Comment by mga47** [comment]
Same here, I also see use it as single view component.  Okay, I'll try to understand their issue in that case, thanks for reply.

**Comment by mga47** [comment]
Closed

**Comment by mga47** [comment]
Closed
