### ISSUE TITLE
Keypad not showing up in landscape mode

### ISSUE THREAD

**Issue by Kodak1234** [fraggjkee/sms-confirmation-view#3]
Keypad does not display when in landscape mode. In textview, the UI enters into full screen mode if in landscape and there isn't enough space. In this case, the keypad does not show at all.

**Comment by Kodak1234** [comment]
Invalid issue

**Comment by Kodak1234** [comment]
Keypad shows up but you can't see entered code unless you hide the keypad

**Comment by fraggjkee** [comment]
Yep, the problem is reproducible on my end, thanks for reporting it. Will take a look as soon as I can.

**Comment by fraggjkee** [comment]
@Kodak1234 Please try version 1.3.1, the issue should have been fixed
