### ISSUE TITLE
Add option to disable permission dialog

### ISSUE THREAD

**Issue by amir14a** [fraggjkee/sms-confirmation-view#5]
Hi.
Some apps don't show permission dialog, but automatically read sms and enter the code, even in Android 10, Android 11.
Can we use this method with your library? how?

**Comment by fraggjkee** [comment]
Hi,

No, the permission-less version cannot be implemented without server-side
support, it’s a two-step process that cannot be done purely from the client
side.

https://developers.google.com/identity/sms-retriever/overview

**Comment by amir14a** [comment]
Oh, Ok thank you
