### ISSUE TITLE
Request: Add custom fontFamily support in XML

### ISSUE THREAD

**Issue by GeniusRUS** [fraggjkee/sms-confirmation-view#6]
It would be great if it was possible to also customize the font type for characters in input cells

So that using a custom font looks like this:
```xml
<com.fraggjkee.smsconfirmationview.SmsConfirmationView
    android:id="@+id/sms_code_view"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    app:scv_symbolTextFontFamily="@font/custom_font" />
```

**Comment by fraggjkee** [comment]
Yeah, good idea, I will consider adding this in one of the next releases 👍I’ll keep this ticket open for now.

**Comment by fmaxx** [comment]
Look at my PR: https://github.com/fraggjkee/sms-confirmation-view/pull/8

**Comment by fraggjkee** [comment]
Hey @fmaxx, thanks for your contribution :) Have merged the PR and increased the library version, closing this issue for now.
